name: Tests

on:
  push:
    branches: ["main", "audit" ]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: bun install
      - run: bun test:commander