name: Tests

on:
  push:
    branches: ["main", "audit" ]
env:
  CI: true

jobs:
  commander-tabtab-test:
    name: Commander Tabtab test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: bun install --frozen-lockfile
      - run: bun test:commander
  init-action-test:
    name: Init action test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: bun install --frozen-lockfile && bun prepublishOnly
      - run: |
          cd example
          ../cli/bin/cursor-rules.js init -h
          ../cli/bin/cursor-rules.js init -f
          ls -la
          test -f ".cursor/rules/cursor-rules.mdc" || { echo "Cursor rule not found"; exit 1; }
          test -f ".cursor/rules/project-structure.mdc" || { echo "Project structure rule not found"; exit 1; }
          test -f ".cursor/rules/task-list.mdc" || { echo "Task list rule not found"; exit 1; }
          test -f ".cursor/rules/use-bun-instead-of-node-vite-npm-pnpm.mdc" || { echo "Bun rule not found"; exit 1; }
          test -f ".cursor/rules/bad-rule.mdc" || { echo "Bad rule not found"; exit 1; }
          test -f "repomix-output.xml" || { echo "Repomix output not found"; exit 1; }
          test -f "repomix.config.json" || { echo "Repomix config not found"; exit 1; }
          echo "Init action test passed"
  repomix-action-test:
    name: Repomix action test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: bun install --frozen-lockfile && bun prepublishOnly
      - run: |
          cd example
          ../cli/bin/cursor-rules.js repomix -h
          ../cli/bin/cursor-rules.js repomix
          ls -la
          test -f "repomix-output.xml" || { echo "Repomix output not found"; exit 1; }
          test -f "repomix.config.json" || { echo "Repomix config not found"; exit 1; }
          echo "Repomix action test passed"
  scan-action-test:
    name: Scan action test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - run: bun install --frozen-lockfile && bun prepublishOnly
      - run: |
          cd example
          ../cli/bin/cursor-rules.js scan -h
          ../cli/bin/cursor-rules.js scan | grep -c "Vulnerable file:" | grep 4 || { echo "Not found"; exit 1;}
          ../cli/bin/cursor-rules.js scan
          ../cli/bin/cursor-rules.js scan | grep "Run cursor-rules scan --sanitize" || { echo "Not found"; exit 1;}
          ../cli/bin/cursor-rules.js scan -s | grep "Fixed 4 files" || { echo "Not found"; exit 1;}
          ../cli/bin/cursor-rules.js scan -s | grep "All files are safe" || { echo "Not found"; exit 1;}
          echo "Scan action test passed"